{% set name = "mofdscribe" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mofdscribe-{{ version }}.tar.gz
  sha256: 8b9b3e471cb122537420065abedf3d0db01a802fb868b008839c34d73bcb361b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matminer
    - loguru
    - pystow
    - ase
    - structuregraph-helpers
    - element-coder
    - pydantic
    - typing-extensions
    - openbabel
    - raspa2

test:
  imports:
    - mofdscribe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kjappelbaum/mofdscribe
  summary: Ecosystem for digital reticular chemistry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
