{% set name = "mofdscribe" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mofdscribe-{{ version }}.tar.gz
  sha256: cc3196ae6949997012d80672fe8e85fe5e83f4053b62c4f88ffd4e5f6e74e96a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matminer
    - loguru
    - pystow
    - ase
    - structuregraph-helpers
    - element-coder
    - pydantic
    - typing-extensions
    - openbabel
    - raspa2
    - zeopp-lsmo
    - moleculetda
    - rdkit

test:
  imports:
    - mofdscribe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kjappelbaum/mofdscribe
  summary: Ecosystem for digital reticular chemistry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
